### ISSUE TITLE
Unknown error when loading account: System.PlatformNotSupportedException: Operation is not supported on this platform.

### ISSUE THREAD

**Issue by fazelukario** [not-ilinked/Anarchy#3227]
When I try to log in with account I getting:
```
Unknown error when loading account:
System.PlatformNotSupportedException: Operation is not supported on this platform.
   at System.Action`1.BeginInvoke(T obj, AsyncCallback callback, Object object)
   at WebSocketSharp.WebSocket.open()
   at WebSocketSharp.WebSocket.Connect()
   at Discord.WebSockets.DiscordWebSocket`1.Connect() in C:\Users\Danylo\Desktop\Anarchy proj\Anarchy\Anarchy\WebSockets\DiscordWebSocket.cs:line 36
   at Discord.Gateway.DiscordSocketClient.Login(String token) in C:\Users\Danylo\Desktop\Anarchy proj\Anarchy\Anarchy\WebSockets\Gateway\DiscordSocketClient.cs:line 206
   at NitroSniperNET.AccountLoader.<LoadAsync>b__5_0() in C:\Users\Danylo\Desktop\Anarchy proj\NitroSniperNET\NitroSniperNET\AccountLoader.cs:line 31
```
Here's part of code thats logging on:
```
public async void LoadAsync()
{
    await Task.Run(() =>
    {
        foreach (var token in Sniper.GetMultiplySettingsSeparatedString(Sniper.SniperSettings.Tokens))
        {
            try
            {
                Sniper client = null;

                DiscordSocketClient sClient = new DiscordSocketClient(new DiscordSocketConfig());
                sClient.OnLoggedIn += Client_OnLoggedIn;
                sClient.Login(token);
                client = new Sniper(sClient);
             }
             catch (InvalidTokenException) { }
             catch (Exception e)
             {
                  Console.WriteLine($"Unknown error when loading account:\n{e}");
             }
          }
     });
}
```

**Comment by not-ilinked** [comment]
Hi. Is your project using .NET Core?

**Comment by fazelukario** [comment]
Yes, .NET Core 3.1

**Comment by not-ilinked** [comment]
Anarchy has some trouble running on .NET Core. Move to .NET Framework and you'll be fine.

**Comment by fazelukario** [comment]
Make a compatibility table like this
![image](https://user-images.githubusercontent.com/46999684/121953685-895f1400-cd66-11eb-9f2d-269b497ad33b.png)
