### ISSUE TITLE
Iuse tring to change only custom status

### ISSUE THREAD

**Issue by Mrgaton** [not-ilinked/Anarchy#3306]
when i try to put custom status like this
![image](https://user-images.githubusercontent.com/68958481/164565063-50183ba7-f21a-47b3-86de-1043f0a7fb71.png)
if you dont put the theme it just throws an exception
so i need to put it but i dont want it

**Comment by not-ilinked** [comment]
Not sure why it would be throwing this error (assuming you're on the latest version), but as a temporary issue do client.User.GetSettings() first to get the current theme, then change their settings

**Comment by Mrgaton** [comment]
i mean if just put the custom status withouth the theme it throws an exception

![image](https://user-images.githubusercontent.com/68958481/165848701-ff725512-4523-439c-ad30-aeb93bcc2ca8.png)
Newtonsoft.Json.JsonSerializationException
  HResult=0x80131500
  Mensaje = Error getting value from 'Theme' on 'Discord.UserSettingsProperties'.
  Origen = Newtonsoft.Json
  Seguimiento de la pila:
   at Newtonsoft.Json.Serialization.DynamicValueProvider.GetValue(Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CalculatePropertyValues(JsonWriter writer, Object value, JsonContainerContract contract, JsonProperty member, JsonProperty property, JsonContract& memberContract, Object& memberValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.JsonConvert.SerializeObject(Object value)
   at Discord.DiscordHttpClient.<SendAsync>d__4.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Discord.DiscordHttpClient.<PatchAsync>d__9.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Discord.DiscordClientUser.<ChangeSettingsAsync>d__41.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Discord.DiscordClientUser.ChangeSettings(UserSettingsProperties settings)
   at GatitoDiscordSpammer.Program.Main(String[] args) in C:\Users\Mrgato\OneDrive\Programas\Programas de CSharp\GatitoDiscordSpammer\GatitoDiscordSpammer\Program.cs:line 182

  Esta excepción se generó originalmente en esta pila de llamadas:
    [Código externo]

Excepción interna 1:
ArgumentNullException: El valor no puede ser nulo.
Nombre del parámetro: value
