### ISSUE TITLE
Error sending file

### ISSUE THREAD

**Issue by Mrgaton** [not-ilinked/Anarchy#3356]
System.ArgumentException: The value cannot be null or empty. (Parameter 'mediaType')
   at System.Net.Http.Headers.MediaTypeHeaderValue.CheckMediaTypeFormat(String mediaType, String parameterName)
   at System.Net.Http.StringContent..ctor(String content, Encoding encoding, String mediaType)
   at Discord.DiscordHttpClient.MakeMultipartFormDataContent(MessageProperties props)
   at Discord.DiscordHttpClient.PostAsync(String endpoint, MessageProperties props)
   at Discord.MessageExtensions.SendMessageAsync(DiscordClient client, UInt64 channelId, MessageProperties properties)
   at Discord.MessageExtensions.SendFileAsync(DiscordClient client, UInt64 channelId, String fileName, Byte[] fileData, String message, Boolean tts)
   at Discord.MinimalTextChannel.SendFileAsync(String fileName, Byte[] fileData, String message, Boolean tts)
   at Discord.MinimalTextChannel.SendFile(String fileName, Byte[] fileData, String message, Boolean tts)

**Comment by Mrgaton** [comment]
Using net 7
